In [1]:
import numpy as np

In [ ]:
np.sum()

In [6]:
A = np.arange(1,7).reshape(3,2)
B = np.array([[5,7,8],[6,2,1]])
C = np.array([[5,7],[2,4]])

In [7]:
BA = np.dot(B, A)
BA

array([[66, 86],
       [17, 26]])

In [8]:
BA+C

array([[71, 93],
       [19, 30]])

In [9]:
5 * C - BA

array([[-41, -51],
       [ -7,  -6]])

In [18]:
C.dot(C).dot(C).dot(C)

array([[2655, 4347],
       [1242, 2034]])

In [12]:
np.trace(BA)

92

In [14]:
#计算行列式
np.linalg.det(BA.dot(C))

1524.0000000000075

In [15]:
#计算方阵的逆
np.linalg.inv(BA)

array([[ 0.1023622 , -0.33858268],
       [-0.06692913,  0.25984252]])

In [16]:
np.linalg.inv(C)

array([[ 0.66666667, -1.16666667],
       [-0.33333333,  0.83333333]])

In [17]:
BA.T

array([[66, 17],
       [86, 26]])

end