## matrhw02

In [1]:
import sys
sys.path.append('d:/github/')

In [2]:
from utils import numpy_wrapper as npwr

In [3]:
npw = npwr.numpy_wrapper()

In [4]:
A = npw.build_array_from_arraylist([[5,2,7],[9,8,3],[1,4,6]])
A

array([[5, 2, 7],
       [9, 8, 3],
       [1, 4, 6]])

In [5]:
B = npw.build_array_from_arraylist([[15,42,63],[21,84,36],[22,76,19]])
B

array([[15, 42, 63],
       [21, 84, 36],
       [22, 76, 19]])

In [6]:
npw.inv(A).dot(B)

array([[-0.81751825, -3.44525547,  6.91240876],
       [ 2.82481752, 12.54744526, -5.37591241],
       [ 1.91970803,  4.87591241,  5.59854015]])

In [7]:
A[0,:].dot(B).T

array([271, 910, 520])

In [8]:
npw.det(5 * A - 3 * B)

1085660.0

In [11]:
npw.sum(A * B)

2009

In [12]:
npw.inv(A.dot(B))

array([[ 0.0776395 , -0.03137091, -0.0366426 ],
       [-0.02043596,  0.00734115,  0.01224788],
       [-0.00277612,  0.00350205, -0.00233736]])

In [13]:
npw.inv(A.dot(B)).dot(A.dot(B))

array([[ 1.00000000e+00,  5.19029264e-15, -1.40165657e-15],
       [ 1.49186219e-16,  1.00000000e+00, -5.65519853e-16],
       [-1.43114687e-17, -1.99493200e-17,  1.00000000e+00]])