## FNHW04

Python文件“MyLogisticRegression.py”里有基于批量梯度上升法求解极大似然函数中的权重参数的代码。  

（1）	结合给出的数据，运行代码，得到权重参数的估计。  
（2）	在（1）权重参数的结果下，计算每个样本属于类别为1的概率  
（3）	以0.5为阈值，概率大于等于该阈值的样本划分为1，否则划分为0.结合真实的标签，计算混淆矩阵，并且计算  
Accuracy  
Precision  
Recall   
Specificity  

In [30]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression,LogisticRegressionCV

In [2]:
def BSD(X,y, w_initial, h=0.01, maxSteps = 100000):   #批量梯度下降法求逻辑回归参数
    '''
    :param X: 输入特征矩阵，第一列为向量1
    :param y: 标签，用1、0表示
    :param w_initial: 初始化权重
    :param h: 固定步长----学习率
    :param maxSteps: 最大迭代步数
    :return: 权重的估计值
    '''
    w0 = w_initial
    for i in range(maxSteps):
        s = np.exp(X*w0)/(1+np.exp(X*w0))
        descent = X.T*y-X.T*s  #梯度
        w1 = w0 + descent*h    #梯度上升
        w0 = w1
        if max(abs(descent*h)) < 0.00001:    #若当前的权重的更新很小时，认为迭代已经收敛，可以提前退出迭代
            break
    return w1

In [3]:
#读取数据，并转换成矩阵
data = pd.read_csv('data.csv',header = 0)
data.head()

X1         X2  Y
0 -0.017612  14.053064  0
1 -1.395634   4.662541  1
2 -0.752157   6.538620  0
3 -1.322371   7.152853  0
4  0.423363  11.054677  0

In [7]:
data2 = np.matrix(data.values)
X,y = data2[:,:2],data2[:,-1]

In [9]:
ones = np.mat(np.ones((X.shape[0],1)))
X = np.hstack((ones, X))
X[:5,:]

matrix([[ 1.      , -0.017612, 14.053064],
        [ 1.      , -1.395634,  4.662541],
        [ 1.      , -0.752157,  6.53862 ],
        [ 1.      , -1.322371,  7.152853],
        [ 1.      ,  0.423363, 11.054677]])

### （1）   结合给出的数据，运行代码，得到权重参数的估计。

In [38]:
#设置初始值，带入批量梯度下降法中
w_initial = np.matrix(np.array([1,1,1])).T
w2 = BSD(X,y, w_initial, 0.01, maxSteps = 100000)
print(w2)

[[14.73245533]
 [ 1.25224897]
 [-2.00004285]]


In [11]:
#同时，用python内置逻辑回归算法求解参数，作为对比
logit = sm.Logit(y, X)
result = logit.fit()
result.summary2()

Optimization terminated successfully.
         Current function value: 0.093158
         Iterations 10


<class 'statsmodels.iolib.summary2.Summary'>
"""
                         Results: Logit
=================================================================
Model:              Logit            Pseudo R-squared: 0.865     
Dependent Variable: y                AIC:              24.6315   
Date:               2018-12-19 13:41 BIC:              32.4470   
No. Observations:   100              Log-Likelihood:   -9.3158   
Df Model:           2                LL-Null:          -69.135   
Df Residuals:       97               LLR p-value:      1.0496e-26
Converged:          1.0000           Scale:            1.0000    
No. Iterations:     10.0000                                      
-------------------------------------------------------------------
           Coef.    Std.Err.      z      P>|z|     [0.025    0.975]
-------------------------------------------------------------------
const     14.7521     4.3948    3.3567   0.0008    6.1385   23.3658
x1         1.2536     0.5770    2.1726   0.0298    0.1227    2.3845
x2        -2.0027     0.5924   -3.3805   0.0007   -3.1638   -0.8416
=================================================================

"""

In [12]:
clf = LogisticRegression()
clf.fit(X[:,1:],y)

/home/ian/installed/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [13]:
clf.coef_

array([[ 0.44732445, -0.58003724]])

In [14]:
clf.intercept_

array([3.83513265])

In [16]:
clf = LogisticRegression(fit_intercept=False)
clf.fit(X,y)

/home/ian/installed/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=False,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [17]:
clf.coef_

array([[ 3.83513265,  0.44732445, -0.58003724]])

In [32]:
clf1 = LogisticRegressionCV(fit_intercept=False)

In [33]:
clf1.fit(X, y)

/home/ian/installed/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
           fit_intercept=False, intercept_scaling=1.0, max_iter=100,
           multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
           refit=True, scoring=None, solver='lbfgs', tol=0.0001, verbose=0)

In [34]:
clf1.coef_

array([[ 9.83133958,  0.90703517, -1.35155844]])

### （2）   在（1）权重参数的结果下，计算每个样本属于类别为1的概率

In [19]:
p = np.exp(X*w2)/(1+np.exp(X*w2))
p

matrix([[1.52071345e-06],
        [9.74900618e-01],
        [6.71074158e-01],
        [2.26269846e-01],
        [1.06128131e-03],
        [7.51527787e-01],
        [4.94128229e-05],
        [1.10841998e-01],
        [2.52730323e-02],
        [2.11448476e-03],
        [8.76147666e-01],
        [4.85872554e-05],
        [9.99948400e-01],
        [3.35084376e-03],
        [9.25853367e-01],
        [9.99997009e-01],
        [9.16692618e-01],
        [9.99909014e-01],
        [9.99998756e-01],
        [9.88945110e-01],
        [9.99978708e-01],
        [9.99998907e-01],
        [7.13496890e-05],
        [9.99999979e-01],
        [9.98803331e-01],
        [5.03616220e-02],
        [1.23171491e-02],
        [9.99998497e-01],
        [9.99690453e-01],
        [6.10844947e-02],
        [9.98111232e-01],
        [2.38582920e-01],
        [9.97831553e-04],
        [9.99999982e-01],
        [9.98215778e-01],
        [1.77998969e-02],
        [3.41039337e-02],
        [1.20570320e-03],
        [1.0

### （3）   以0.5为阈值，概率大于等于该阈值的样本划分为1，否则划分为0.结合真实的标签，计算混淆矩阵，并且计算
Accuracy
Precision
Recall
Specificity

In [20]:
p1 = pd.DataFrame(p,columns=['p'])

In [21]:
p1['y_test'] = 1

In [22]:
p1['y_test'][p1['p']<0.5]=0

/home/ian/installed/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [23]:
p1['y']=data['Y']

In [24]:
p1.head()

p  y_test  y
0  0.000002       0  0
1  0.974901       1  1
2  0.671074       1  0
3  0.226270       0  0
4  0.001061       0  0

In [25]:
m = p1.groupby(['y','y_test']).count()
m

p
y y_test    
0 0       44
  1        3
1 0        2
  1       51

In [26]:
from sklearn.metrics import accuracy_score, classification_report

In [27]:
print("accuracy score: ")
print(accuracy_score(p1['y'], p1['y_test']))
print(classification_report(p1['y'], p1['y_test']))

accuracy score: 
0.95
             precision    recall  f1-score   support

          0       0.96      0.94      0.95        47
          1       0.94      0.96      0.95        53

avg / total       0.95      0.95      0.95       100



In [29]:
print("accuracy score: ")
print(accuracy_score(p1['y'], clf.predict(X)))
print(classification_report(p1['y'], clf.predict(X)))

accuracy score: 
0.96
             precision    recall  f1-score   support

          0       0.92      1.00      0.96        47
          1       1.00      0.92      0.96        53

avg / total       0.96      0.96      0.96       100



In [35]:
print("accuracy score: ")
print(accuracy_score(p1['y'], clf1.predict(X)))
print(classification_report(p1['y'], clf1.predict(X)))

accuracy score: 
0.95
             precision    recall  f1-score   support

          0       0.96      0.94      0.95        47
          1       0.94      0.96      0.95        53

avg / total       0.95      0.95      0.95       100



### sklearn中的LogisticRegression加入了正则项，预测的结果比不加正则会好一些; LogisticRegressionCV的效果和自己计算的效果差不多

In [55]:
m.iloc[2,0]

2

In [56]:
TP,FN,FP,TN = m.iloc[3,0],m.iloc[2,0],m.iloc[1,0],m.iloc[0,0]
TP,FN,FP,TN

(51, 2, 3, 44)

In [57]:
Accuracy = (TP+TN)/(TP+TN+FP+FN)
Accuracy

0.95

In [58]:
Precision = TP/(TP+FP)
Precision

0.9444444444444444

In [59]:
Recall = TP/(TP+FN)
Specificity = TN/(TN+FP)
Recall, Specificity

(0.9622641509433962, 0.9361702127659575)